# Generated by Django 5.0 on 2024-01-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dealNumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('frontEnd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('dealNumber', models.IntegerField(unique=True)),
                ('backend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(choices=[(1, '1'), (0.5, '0.5')], decimal_places=1, default=1, max_digits=2)),
            ],
        ),
    ]
