# Generated by Django 5.0 on 2024-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='count',
            field=models.DecimalField(choices=[(2, '2'), (1, '1'), (0.5, '0.5')], decimal_places=1, default=1, max_digits=2),
        ),
    ]
