# Generated by Django 5.0 on 2024-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0002_alter_sale_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_percent', models.DecimalField(decimal_places=3, max_digits=4)),
                ('adjustable_value_1', models.DecimalField(decimal_places=2, default=250, max_digits=4)),
                ('adjustable_value_2', models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
            ],
        ),
    ]
