# Generated by Django 5.0 on 2024-01-09 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0003_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='adjustable_value_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('250'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='commission',
            name='front_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
    ]
