# Generated by Django 5.0 on 2024-01-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0004_alter_commission_adjustable_value_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='front_min',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='front_percent',
        ),
    ]
