# Generated by Django 5.0 on 2024-01-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0005_remove_commission_front_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='adjustable_value_1',
            new_name='frontend_minimum',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='adjustable_value_2',
            new_name='frontend_percentage',
        ),
    ]
