# Generated by Django 5.0 on 2024-01-09 22:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0006_rename_adjustable_value_1_commission_frontend_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='backend_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.003'), max_digits=4),
        ),
    ]
