# Generated by Django 5.0 on 2024-01-16 20:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0007_commission_backend_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='backend_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.03'), max_digits=4),
        ),
    ]
