# Generated by Django 5.0 on 2024-01-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0008_alter_commission_backend_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('amount_awarded', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='bonus_levels',
            field=models.ManyToManyField(blank=True, to='SalesLogApp.bonuslevel'),
        ),
    ]
