# Generated by Django 5.0 on 2024-01-16 21:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0009_bonuslevel_commission_bonus_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='backend_percentage',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4),
        ),
    ]
