# Generated by Django 5.0 on 2024-08-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0010_alter_commission_backend_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonuslevel',
            old_name='amount_awarded',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='bonuslevel',
            name='commission',
            field=models.ForeignKey(default=2500, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_levels', to='SalesLogApp.commission'),
            preserve_default=False,
        ),
    ]
