# Generated by Django 5.0 on 2024-08-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0011_rename_amount_awarded_bonuslevel_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('deal_number', models.IntegerField()),
                ('count', models.IntegerField()),
                ('front_end_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('back_end_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('archived_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bonuslevel',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_levels_set', to='SalesLogApp.commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='bonus_levels',
            field=models.ManyToManyField(blank=True, related_name='commissions', to='SalesLogApp.bonuslevel'),
        ),
    ]
