# Generated by Django 5.1.1 on 2024-09-08 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0016_alter_bonuslevel_user_alter_commission_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='backend_percentage',
            new_name='total_calculated_back_end',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='frontend_percentage',
            new_name='total_calculated_front_end',
        ),
        migrations.AlterField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
