# Generated by Django 5.1.1 on 2024-09-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0017_rename_backend_percentage_commission_total_calculated_back_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuslevel',
            name='custom_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bonuslevel',
            name='toggle_custom_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
