# Generated by Django 5.1.1 on 2024-09-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0018_bonuslevel_custom_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='backend_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='backend_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='frontend_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='opt_out_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='opt_out_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='toggle_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='frontend_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='total_calculated_front_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
