# Generated by Django 5.1.1 on 2024-09-12 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0019_commission_backend_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='total_calculated_front_end',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
