# Generated by Django 5.1.1 on 2024-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0020_alter_commission_total_calculated_front_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuslevel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonuslevel',
            name='tied_to_units',
            field=models.BooleanField(default=False),
        ),
    ]
