# Generated by Django 5.1.1 on 2024-09-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0021_bonuslevel_active_bonuslevel_tied_to_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonuslevel',
            old_name='level',
            new_name='count',
        ),
    ]
