# Generated by Django 5.1.1 on 2024-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0022_rename_level_bonuslevel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuslevel',
            name='criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bonuslevel',
            name='max_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonuslevel',
            name='min_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
