# Generated by Django 5.1.1 on 2024-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0023_bonuslevel_criteria_bonuslevel_max_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedsale',
            old_name='back_end_total',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='archivedsale',
            old_name='sale_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='archivedsale',
            old_name='front_end_total',
            new_name='frontEnd',
        ),
        migrations.RenameField(
            model_name='bonuslevel',
            old_name='count',
            new_name='count_threshold',
        ),
        migrations.RemoveField(
            model_name='archivedsale',
            name='deal_number',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='custom_bonus',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='max_units',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='min_units',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='tied_to_units',
        ),
        migrations.RemoveField(
            model_name='bonuslevel',
            name='toggle_custom_bonus',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='toggle_bonus',
        ),
        migrations.AddField(
            model_name='archivedsale',
            name='dealNumber',
            field=models.IntegerField(default=12544, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedsale',
            name='count',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='sale',
            name='count',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
