# Generated by Django 5.1.1 on 2024-09-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0024_rename_back_end_total_archivedsale_backend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuslevel',
            name='tied_to_units',
            field=models.BooleanField(default=False),
        ),
    ]
