# Generated by Django 5.1.1 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0025_bonuslevel_tied_to_units'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bonuslevel',
            index=models.Index(
                fields=['commission', 'active', 'count_threshold'],
                name='bonus_comm_active_count_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(
                fields=['user', 'date'],
                name='sale_user_date_idx',
            ),
        ),
    ]
