# Generated by Django 5.2.15 on 2026-07-25 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0035_seed_automotive_pay_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN without I, O, or Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.CreateModel(
            name='PayPlanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(max_length=64)),
                ('calculation_scope', models.CharField(max_length=16)),
                ('condition_group_operator', models.CharField(choices=[('all', 'All'), ('any', 'Any')], default='all', max_length=8)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='SalesLogApp.payplanversion')),
            ],
            options={
                'ordering': ['pay_plan_version', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayPlanRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('operator', models.CharField(max_length=32)),
                ('value', models.JSONField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='SalesLogApp.payplanrule')),
            ],
            options={
                'ordering': ['rule', 'sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payplanrule',
            index=models.Index(fields=['pay_plan_version', 'is_active', 'sort_order'], name='payplanrule_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='payplanrulecondition',
            index=models.Index(fields=['rule', 'field_name', 'operator'], name='pprcondition_rule_field_idx'),
        ),
    ]
