# Generated by Django 5.2.15 on 2026-07-26 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0036_add_pay_plan_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commission_system',
            field=models.CharField(choices=[('legacy', 'Legacy commission system'), ('new_engine', 'New pay-plan engine')], db_index=True, default='legacy', max_length=20),
        ),
        migrations.CreateModel(
            name='PayPlanOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('method_selected', 'Method selected'), ('submitted', 'Submitted'), ('draft_created', 'Draft created'), ('needs_review', 'Needs review'), ('ready_to_activate', 'Ready to activate'), ('active', 'Active'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=32)),
                ('setup_method', models.CharField(blank=True, choices=[('upload', 'Upload'), ('describe', 'Describe'), ('manual_builder', 'Manual builder'), ('assisted', 'Assisted')], max_length=32)),
                ('questionnaire', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_pay_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='SalesLogApp.payplan')),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='SalesLogApp.payplanversion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPlanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pay_plan_documents/%Y/%m/')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('pending_review', 'Pending review'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=32)),
                ('page_order', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='SalesLogApp.payplan')),
                ('pay_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='SalesLogApp.payplanversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_documents', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='SalesLogApp.payplanonboarding')),
            ],
        ),
        migrations.CreateModel(
            name='PayPlanDescriptionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_submissions', to='SalesLogApp.payplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_descriptions', to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_submissions', to='SalesLogApp.payplanonboarding')),
            ],
        ),
        migrations.AddIndex(
            model_name='payplanonboarding',
            index=models.Index(fields=['user', 'status'], name='pp_o_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payplanonboarding',
            index=models.Index(fields=['status', 'setup_method'], name='pp_o_status_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payplandocument',
            index=models.Index(fields=['user', 'status'], name='payplan_doc_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payplandocument',
            index=models.Index(fields=['onboarding', 'document_type'], name='payplan_doc_onboard_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payplandescriptionsubmission',
            index=models.Index(fields=['user', 'status'], name='payplan_desc_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payplandescriptionsubmission',
            index=models.Index(fields=['onboarding', 'status'], name='pp_desc_onboard_status_idx'),
        ),
    ]
