# Generated by Django 5.2.15 on 2026-07-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0037_userprofile_commission_system_payplanonboarding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payplandocument',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payplandocument',
            name='parser_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplandocument',
            name='processing_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payplandocument',
            name='processing_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='activation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pay_plan_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='parser_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_versions', to='SalesLogApp.payplanversion'),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='processing_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='processing_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='processing_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='source_type',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('upload', 'Upload'), ('reload', 'Reload'), ('manual', 'Manual')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payplanversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review_required', 'Review Required'), ('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Processing Failed'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commission_system',
            field=models.CharField(choices=[('legacy', 'Legacy commission system'), ('pay_plan_v2', 'Pay Plan engine'), ('new_engine', 'New pay-plan engine (legacy value)')], db_index=True, default='legacy', max_length=20),
        ),
        migrations.CreateModel(
            name='PayPlanActivationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Activated'), ('recalculated', 'Recalculated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_activation_events', to='SalesLogApp.payplanversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_activation_events', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_events', to='SalesLogApp.payplanversion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
