# Generated by Django 5.2.15 on 2026-07-26 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0038_pay_plan_replacement_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPlanEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField()),
                ('green_pea', models.BooleanField(blank=True, help_text='Whether the Green Pea program applies for this month.', null=True)),
                ('nps_status', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Not eligible'), ('exempt', 'Exempt'), ('pending', 'Pending or unknown')], default='pending', max_length=16)),
                ('training_requirements_met', models.BooleanField(blank=True, null=True)),
                ('call_requirement_met', models.BooleanField(blank=True, null=True)),
                ('video_requirement_met', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pay_plan_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_start', '-id'],
                'indexes': [models.Index(fields=['user', 'month_start'], name='ppeligibility_user_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'month_start'), name='unique_payplan_eligibility_month'), models.CheckConstraint(condition=models.Q(('month_start__day', 1)), name='payplan_eligibility_month_first')],
            },
        ),
    ]
