# Generated by Django 5.2.15 on 2026-07-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0039_monthly_pay_plan_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedsale',
            name='vehicle_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], default='', help_text='Required when the pay plan has different new and used rules.', max_length=8),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], default='', help_text='Required when the pay plan has different new and used rules.', max_length=8),
        ),
    ]
