# Generated by Django 5.2.15 on 2026-07-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0040_archivedsale_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payplanversion',
            name='source_type',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('upload', 'Upload'), ('reload', 'Reload'), ('manual', 'Manual'), ('paste', 'Pasted text')], default='legacy', max_length=16),
        ),
    ]
