# Generated by Django 5.2.15 on 2026-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0041_alter_payplanversion_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplaneligibility',
            name='ar_requirement_met',
            field=models.BooleanField(blank=True, help_text='Whether the active plan’s AR requirement is met this month.', null=True),
        ),
    ]
