# Generated by Django 5.2.15 on 2026-07-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0042_payplaneligibility_ar_requirement_met'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplanversion',
            name='default_backend_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='default_backend_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='default_backend_percentage',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Canonical backend multiplier, for example 0.05 for 5%.', max_digits=7, null=True),
        ),
    ]
