# Generated by Django 5.2.15 on 2026-07-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0043_payplanversion_default_backend_maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedsale',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('street_curb', 'Street / Curb'), ('current_service_customer', 'Current Service Customer'), ('trade_in', 'Trade-in'), ('auction', 'Auction'), ('dealer_purchase', 'Dealer purchase'), ('other', 'Other')], default='', help_text='Select how the dealership acquired this vehicle, when applicable.', max_length=32),
        ),
        migrations.AddField(
            model_name='archivedsale',
            name='custom_pay_plan_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional sale-level facts requested by an imported pay plan.'),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict, help_text='Additional monthly facts requested by an imported pay plan.'),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='holiday_bonus_eligible',
            field=models.BooleanField(blank=True, help_text='Whether Holiday Bonus Fund accrual is currently eligible.', null=True),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='holiday_bonus_forfeited',
            field=models.BooleanField(default=False, help_text='Whether accrued Holiday Bonus Fund money has been forfeited.'),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_low_score_surveys',
            field=models.PositiveIntegerField(default=0, help_text='Number of returned NPS surveys scored 8 or below.'),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_qualifying_surveys',
            field=models.PositiveIntegerField(default=0, help_text='Number of returned NPS surveys with a qualifying score.'),
        ),
        migrations.AddField(
            model_name='sale',
            name='acquisition_source',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('street_curb', 'Street / Curb'), ('current_service_customer', 'Current Service Customer'), ('trade_in', 'Trade-in'), ('auction', 'Auction'), ('dealer_purchase', 'Dealer purchase'), ('other', 'Other')], default='', help_text='Select how the dealership acquired this vehicle, when applicable.', max_length=32),
        ),
        migrations.AddField(
            model_name='sale',
            name='custom_pay_plan_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional sale-level facts requested by an imported pay plan.'),
        ),
        migrations.AlterField(
            model_name='archivedsale',
            name='vehicle_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('retired_sslp', 'Retired SSLP')], default='', help_text='Required when the pay plan has different new and used rules.', max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vehicle_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('retired_sslp', 'Retired SSLP')], default='', help_text='Required when the pay plan has different new and used rules.', max_length=16),
        ),
    ]
