# Generated by Django 5.2.15 on 2026-07-27 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0044_pay_plan_dynamic_data_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPlanChangePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('target_key', models.CharField(max_length=128)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('example_request', models.TextField(blank=True)),
                ('last_approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action_type', 'target_key'), name='unique_payplan_change_pattern')],
            },
        ),
        migrations.CreateModel(
            name='PayPlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('parsed_actions', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='needs_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('draft_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plain_text_change_request', to='SalesLogApp.payplanversion')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plain_text_source_requests', to='SalesLogApp.payplanversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='ppchange_user_status_idx')],
            },
        ),
    ]
