# Generated by Django 5.2.15 on 2026-07-27 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0045_plain_language_pay_plan_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payplanversion',
            name='canonical_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='canonical_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='canonical_schema_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='compilation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payplanversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review_required', 'Review Required'), ('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Processing Failed'), ('archived', 'Archived'), ('future_effective', 'Future Effective')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='PayPlanConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('selected_rule_key', models.CharField(blank=True, max_length=150)),
                ('pending_intent', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='SalesLogApp.payplanversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPlanConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('structured_intent', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='SalesLogApp.payplanconversation')),
            ],
            options={
                'ordering': ['conversation', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='payplanconversation',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='pp_conv_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payplanconversation',
            constraint=models.UniqueConstraint(fields=('user', 'conversation_key'), name='unique_payplan_conversation_key_per_user'),
        ),
        migrations.AddConstraint(
            model_name='payplanconversationturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='unique_payplan_conversation_turn_sequence'),
        ),
    ]
