# Generated by Django 5.2.15 on 2026-07-27 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0046_payplanversion_canonical_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payplanversion',
            name='is_sandbox',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CommissionSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scenario_name', models.CharField(max_length=150)),
                ('scenario_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_session', to='SalesLogApp.payplanversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_sandboxes', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_sandboxes', to='SalesLogApp.payplanversion')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SandboxHypotheticalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('count', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('split_with_name', models.CharField(blank=True, default='', max_length=100)),
                ('frontEnd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('vehicle_condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('retired_sslp', 'Retired SSLP')], default='', help_text='Required when the pay plan has different new and used rules.', max_length=16)),
                ('acquisition_source', models.CharField(blank=True, choices=[('', 'Not applicable'), ('street_curb', 'Street / Curb'), ('current_service_customer', 'Current Service Customer'), ('trade_in', 'Trade-in'), ('auction', 'Auction'), ('dealer_purchase', 'Dealer purchase'), ('other', 'Other')], default='', help_text='Select how the dealership acquired this vehicle, when applicable.', max_length=32)),
                ('custom_pay_plan_fields', models.JSONField(blank=True, default=dict, help_text='Additional sale-level facts requested by an imported pay plan.')),
                ('sale_type', models.CharField(choices=[('automotive', 'Automotive')], db_index=True, default='automotive', max_length=32)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('dealNumber', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothetical_deals', to='SalesLogApp.commissionsandbox')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SandboxRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('replay', 'Historical replay'), ('projection', 'Future projection'), ('mixed', 'Historical and hypothetical')], max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('sandbox_revision', models.PositiveIntegerField()),
                ('input_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('actual_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sandbox_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='SalesLogApp.commissionsandbox')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SandboxResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sandbox_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('comparison', models.CharField(choices=[('higher', 'Higher'), ('lower', 'Lower'), ('unchanged', 'Unchanged')], max_length=16)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hypothetical_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='SalesLogApp.sandboxhypotheticaldeal')),
                ('production_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_results', to='SalesLogApp.sale')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='SalesLogApp.sandboxrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='commissionsandbox',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='sandbox_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sandboxhypotheticaldeal',
            constraint=models.UniqueConstraint(fields=('sandbox', 'dealNumber'), name='unique_sandbox_hypothetical_deal'),
        ),
        migrations.AddIndex(
            model_name='sandboxrun',
            index=models.Index(fields=['sandbox', 'sandbox_revision', 'created_at'], name='sandbox_run_revision_idx'),
        ),
        migrations.AddConstraint(
            model_name='sandboxresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hypothetical_deal__isnull', True), ('production_sale__isnull', False)), models.Q(('hypothetical_deal__isnull', False), ('production_sale__isnull', True)), _connector='OR'), name='sandbox_result_exactly_one_deal'),
        ),
    ]
