# Generated by Django 5.2.15 on 2026-07-27 22:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


SEMANTIC_KEY_NAMESPACE = uuid.UUID('9b322cc3-aa02-41a3-a61c-86e6f76aa6db')


def _serialized_value(value):
    if value is None:
        return None
    if hasattr(value, 'isoformat'):
        return value.isoformat()
    return str(value)


def _deal_snapshot(deal):
    if deal is None:
        return {}
    return {
        'id': deal.pk,
        'deal_number': getattr(deal, 'dealNumber', None),
        'customer': getattr(deal, 'customer', ''),
        'date': _serialized_value(getattr(deal, 'date', None)),
        'unit_count': _serialized_value(getattr(deal, 'count', None)),
        'front_end_gross': _serialized_value(getattr(deal, 'frontEnd', None)),
        'back_end_gross': _serialized_value(getattr(deal, 'backend', None)),
        'vehicle_condition': getattr(deal, 'vehicle_condition', '') or '',
        'acquisition_source': getattr(deal, 'acquisition_source', '') or '',
        'sale_type': getattr(deal, 'sale_type', '') or '',
        'custom_pay_plan_fields': (
            getattr(deal, 'custom_pay_plan_fields', None) or {}
        ),
        'label': getattr(deal, 'label', '') or '',
    }


def _available_scenario_name(raw_name, sandbox_id, used_names):
    base = (raw_name or '').strip() or f'Scenario {sandbox_id}'
    base = base[:150]
    candidate = base
    suffix_number = 2
    while candidate.casefold() in used_names:
        suffix = f' ({suffix_number})'
        candidate = f'{base[:150 - len(suffix)]}{suffix}'
        suffix_number += 1
    used_names.add(candidate.casefold())
    return candidate


def backfill_scenario_data(apps, schema_editor):
    CommissionSandbox = apps.get_model('SalesLogApp', 'CommissionSandbox')
    PayPlanRule = apps.get_model('SalesLogApp', 'PayPlanRule')
    SandboxResult = apps.get_model('SalesLogApp', 'SandboxResult')
    SandboxRun = apps.get_model('SalesLogApp', 'SandboxRun')
    ScenarioHistory = apps.get_model('SalesLogApp', 'ScenarioHistory')

    names_by_owner = {}
    sandboxes = CommissionSandbox.objects.order_by(
        'owner_id', 'created_at', 'id',
    )
    for sandbox in sandboxes.iterator():
        if sandbox.status == 'archived':
            normalized_name = (
                (sandbox.scenario_name or '').strip()
                or f'Scenario {sandbox.pk}'
            )[:150]
        else:
            used_names = names_by_owner.setdefault(sandbox.owner_id, set())
            normalized_name = _available_scenario_name(
                sandbox.scenario_name,
                sandbox.pk,
                used_names,
            )

        latest_run = SandboxRun.objects.filter(
            sandbox_id=sandbox.pk,
        ).order_by('-created_at', '-id').first()

        sandbox.scenario_name = normalized_name
        sandbox.saved_revision = sandbox.revision
        sandbox.last_saved_at = sandbox.updated_at or sandbox.created_at
        update_fields = [
            'scenario_name',
            'saved_revision',
            'last_saved_at',
        ]

        if latest_run is not None:
            sandbox.replay_mode = latest_run.mode
            sandbox.replay_start_date = latest_run.period_start
            sandbox.replay_end_date = latest_run.period_end
            sandbox.last_calculated_at = latest_run.created_at
            sandbox.last_calculated_revision = latest_run.sandbox_revision
            sandbox.calculation_input_fingerprint = (
                latest_run.input_fingerprint or ''
            )
            # These values cannot be inferred reliably for pre-5B runs.
            # Keeping them blank intentionally makes the saved result stale.
            sandbox.calculation_engine_version = ''
            sandbox.calculation_source_fingerprint = ''
            sandbox.calculation_summary = {
                'currency': 'USD',
                'live_total': str(latest_run.actual_total),
                'scenario_total': str(latest_run.sandbox_total),
                'difference': str(latest_run.difference),
                'percentage_change': (
                    str(latest_run.percent_change)
                    if latest_run.percent_change is not None
                    else None
                ),
                'statistics': latest_run.statistics or {},
                'migrated_from_run_id': latest_run.pk,
            }
            sandbox.validation_summary = latest_run.validation_report or {}
            update_fields.extend([
                'replay_mode',
                'replay_start_date',
                'replay_end_date',
                'last_calculated_at',
                'last_calculated_revision',
                'calculation_input_fingerprint',
                'calculation_engine_version',
                'calculation_source_fingerprint',
                'calculation_summary',
                'validation_summary',
            ])

        sandbox.save(update_fields=update_fields)
        ScenarioHistory.objects.create(
            scenario_id=sandbox.pk,
            actor_id=sandbox.owner_id,
            action='scenario_migrated',
            summary='Existing sandbox session preserved as a scenario.',
            metadata={
                'migration': '0048_scenariohistory_and_more',
                'legacy_sandbox': True,
            },
        )

    for rule in PayPlanRule.objects.filter(
        semantic_key__isnull=True,
    ).iterator():
        rule.semantic_key = uuid.uuid5(
            SEMANTIC_KEY_NAMESPACE,
            f'pay-plan-rule:{rule.pk}',
        )
        rule.save(update_fields=['semantic_key'])

    results = SandboxResult.objects.select_related(
        'production_sale',
        'hypothetical_deal',
    ).order_by('id')
    for result in results.iterator():
        if result.hypothetical_deal_id is not None:
            result.deal_kind = 'hypothetical'
            result.source_key = (
                f'hypothetical:{result.hypothetical_deal_id}'
            )
            source_deal = result.hypothetical_deal
        else:
            result.deal_kind = 'production'
            result.source_key = (
                f'production:{result.production_sale_id}'
                if result.production_sale_id is not None
                else f'production:missing:{result.pk}'
            )
            source_deal = result.production_sale
        result.sale_snapshot = _deal_snapshot(source_deal)
        result.save(update_fields=[
            'deal_kind',
            'source_key',
            'sale_snapshot',
        ])


def reverse_scenario_data(apps, schema_editor):
    PayPlanRule = apps.get_model('SalesLogApp', 'PayPlanRule')
    SandboxResult = apps.get_model('SalesLogApp', 'SandboxResult')
    ScenarioHistory = apps.get_model('SalesLogApp', 'ScenarioHistory')

    ScenarioHistory.objects.filter(action='scenario_migrated').delete()
    PayPlanRule.objects.update(semantic_key=None)
    SandboxResult.objects.update(
        deal_kind=None,
        source_key='',
        sale_snapshot={},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0047_payplanversion_is_sandbox_commissionsandbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sandboxresult',
            name='sandbox_result_exactly_one_deal',
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='assumptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='calculation_engine_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='calculation_input_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='calculation_source_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='calculation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='last_calculated_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='replay_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='replay_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='replay_mode',
            field=models.CharField(
                choices=[
                    ('replay', 'Historical replay'),
                    ('projection', 'Future projection'),
                    ('mixed', 'Historical and hypothetical'),
                ],
                default='replay',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='replay_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='saved_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='source_scenario',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplicates',
                to='SalesLogApp.commissionsandbox',
            ),
        ),
        migrations.AddField(
            model_name='commissionsandbox',
            name='validation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payplanrule',
            name='semantic_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payplanversion',
            name='origin_scenario',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='converted_version',
                to='SalesLogApp.commissionsandbox',
            ),
        ),
        migrations.AddField(
            model_name='sandboxresult',
            name='actual_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sandboxresult',
            name='deal_kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('production', 'Production sale'),
                    ('hypothetical', 'Hypothetical sale'),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='sandboxresult',
            name='sale_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sandboxresult',
            name='source_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sandboxrun',
            name='engine_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sandboxrun',
            name='live_version_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sandboxrun',
            name='schema_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sandboxrun',
            name='source_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='commissionsandbox',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('shared', 'Shared'),
                    ('archived', 'Archived'),
                    ('converted', 'Converted to Pay Plan'),
                ],
                db_index=True,
                default='draft',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxresult',
            name='hypothetical_deal',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='results',
                to='SalesLogApp.sandboxhypotheticaldeal',
            ),
        ),
        migrations.AlterField(
            model_name='sandboxresult',
            name='production_sale',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sandbox_results',
                to='SalesLogApp.sale',
            ),
        ),
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('action', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='commission_scenario_history',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'scenario',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='history',
                        to='SalesLogApp.commissionsandbox',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(
            backfill_scenario_data,
            reverse_scenario_data,
        ),
        migrations.AlterField(
            model_name='payplanrule',
            name='semantic_key',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxresult',
            name='deal_kind',
            field=models.CharField(
                choices=[
                    ('production', 'Production sale'),
                    ('hypothetical', 'Hypothetical sale'),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name='commissionsandbox',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim('scenario_name'),
                ),
                models.F('owner'),
                condition=models.Q(status='archived', _negated=True),
                name='unique_open_scenario_name_ci',
            ),
        ),
        migrations.AddConstraint(
            model_name='commissionsandbox',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(replay_end_date__isnull=True)
                    | models.Q(replay_start_date__isnull=True)
                    | models.Q(
                        replay_end_date__gte=models.F('replay_start_date'),
                    )
                ),
                name='scenario_valid_replay_dates',
            ),
        ),
        migrations.AddConstraint(
            model_name='commissionsandbox',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    saved_revision__lte=models.F('revision'),
                ),
                name='scenario_saved_revision_lte_revision',
            ),
        ),
        migrations.AddConstraint(
            model_name='payplanrule',
            constraint=models.UniqueConstraint(
                fields=('pay_plan_version', 'semantic_key'),
                name='unique_rule_semantic_key_per_version',
            ),
        ),
        migrations.AddConstraint(
            model_name='sandboxresult',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        deal_kind='production',
                        hypothetical_deal__isnull=True,
                    )
                    | models.Q(
                        deal_kind='hypothetical',
                        production_sale__isnull=True,
                    )
                ),
                name='sandbox_result_valid_deal_kind',
            ),
        ),
        migrations.AddIndex(
            model_name='scenariohistory',
            index=models.Index(
                fields=['scenario', 'created_at'],
                name='scenario_history_date_idx',
            ),
        ),
    ]
