# Generated by Django 5.2.15 on 2026-08-05

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0048_scenariohistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Current monthly Net Promoter Score, from -100 through 100.',
                max_digits=5,
                null=True,
                validators=[MinValueValidator(-100), MaxValueValidator(100)],
            ),
        ),
    ]
