# Generated by Django 5.2.15 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0049_payplaneligibility_nps_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payplaneligibility',
            name='nps_score',
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_projection_passing',
            field=models.BooleanField(
                blank=True,
                help_text='Private user-entered assumption for the monthly NPS projection.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_projected_bad_surveys',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Private projected count of bad surveys for this month.',
            ),
        ),
        migrations.AddField(
            model_name='payplaneligibility',
            name='nps_projected_good_surveys',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Private projected count of good surveys for this month.',
            ),
        ),
    ]
