# Generated by Django 5.2.15 on 2026-08-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0051_pay_plan_conversation_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPlanAssistantUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('interpretation', 'Interpretation')], default='interpretation', max_length=32)),
                ('route', models.CharField(choices=[('deterministic', 'Deterministic'), ('provider', 'Provider')], max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('timeout', 'Timeout'), ('refusal', 'Refusal'), ('unavailable', 'Unavailable'), ('invalid_output', 'Invalid output'), ('rate_limited', 'Rate limited'), ('disabled', 'Disabled'), ('rollout_excluded', 'Rollout excluded'), ('configuration_error', 'Configuration error')], max_length=32)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('duration_bucket', models.CharField(max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('conversation_ref', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='draft_change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_conversations', to='SalesLogApp.payplanchangerequest'),
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='draft_submission_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='interpretation_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='processing_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplanconversation',
            name='start_submission_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payplanconversationturn',
            name='submission_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='payplanconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('start_submission_token', ''), _negated=True), fields=('user', 'start_submission_token'), name='unique_pp_conv_start_token_user'),
        ),
        migrations.AddConstraint(
            model_name='payplanconversationturn',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_token', ''), _negated=True), fields=('conversation', 'submission_token'), name='unique_pp_turn_submission_token'),
        ),
        migrations.AddField(
            model_name='payplanassistantusageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_plan_assistant_usage_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payplanassistantusageevent',
            index=models.Index(fields=['user', 'route', 'created_at'], name='pp_usage_user_route_time_idx'),
        ),
        migrations.AddIndex(
            model_name='payplanassistantusageevent',
            index=models.Index(fields=['status', 'created_at'], name='pp_usage_status_time_idx'),
        ),
    ]
