# Generated by Django 5.2.15 on 2026-08-10 14:27

import SalesLogApp.models.teams
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0052_payplanassistantusageevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[SalesLogApp.models.teams.validate_timezone_name])),
                ('monthly_unit_goal', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('display_mode', models.CharField(choices=[('ranked', 'Ranked by units'), ('alphabetical', 'Alphabetical')], default='ranked', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_sales_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(choices=[('sale', 'Sale'), ('milestone', 'Milestone')], default='sale', max_length=16)),
                ('unit_credit', models.DecimalField(decimal_places=1, max_digits=5)),
                ('activity_date', models.DateField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_activity', to='SalesLogApp.sale')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='SalesLogApp.team')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('intended_email', models.EmailField(blank=True, max_length=254)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_sales_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('intended_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='SalesLogApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('declined', 'Declined'), ('removed', 'Removed'), ('left', 'Left')], default='invited', max_length=12)),
                ('sharing_preference', models.CharField(choices=[('individual_and_totals', 'Individual activity and totals'), ('totals_only', 'Totals only'), ('paused', 'Pause all sharing')], default='totals_only', max_length=28)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='SalesLogApp.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SalesLogApp.teamactivity')),
                ('author_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='SalesLogApp.teammembership')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_comments', to='SalesLogApp.teammembership')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='teamactivity',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='SalesLogApp.teammembership'),
        ),
        migrations.CreateModel(
            name='TeamReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('celebrate', 'Celebrate'), ('on_fire', 'On fire'), ('applause', 'Applause'), ('strong_work', 'Strong work'), ('great_job', 'Great job')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='SalesLogApp.teamactivity')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='SalesLogApp.teammembership')),
            ],
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner', 'is_active'], name='team_owner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_unit_goal__isnull', True), ('monthly_unit_goal__gt', 0), _connector='OR'), name='team_monthly_goal_positive'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['intended_user', 'expires_at'], name='team_invitee_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['team', 'accepted_at', 'revoked_at'], name='team_invite_state_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status'], name='team_member_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status', 'role'], name='team_member_status_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_user_membership'),
        ),
        migrations.AddIndex(
            model_name='teamcomment',
            index=models.Index(fields=['activity', 'created_at'], name='team_comment_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivity',
            index=models.Index(fields=['team', 'is_visible', 'activity_date'], name='team_activity_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='teamreaction',
            index=models.Index(fields=['activity', 'code'], name='team_reaction_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamreaction',
            constraint=models.UniqueConstraint(fields=('activity', 'membership', 'code'), name='unique_team_activity_reaction'),
        ),
    ]
