# Generated by Django 5.2.15 on 2026-08-11 00:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0053_phase2a_teams'),
        ('djstripe', '0003_2_11'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('code_prefix', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveSmallIntegerField(default=1)),
                ('redemption_count', models.PositiveSmallIntegerField(default=0)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('trial_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('entitlement_tier', models.CharField(choices=[('founder_pro', 'Founder Pro')], default='founder_pro', max_length=24)),
                ('administrative_note', models.TextField(blank=True, help_text='Never enter payment, card, customer, or other billing data.', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_founder_grants', to=settings.AUTH_USER_MODEL)),
                ('redeemed_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_founder_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingCheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trial_kind', models.CharField(blank=True, choices=[('', 'None'), ('standard', 'Standard'), ('founder', 'Founder')], default='', max_length=12)),
                ('trial_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365)])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('session_created', 'Session created'), ('checkout_completed', 'Checkout completed'), ('confirmed', 'Subscription confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='reserved', max_length=20)),
                ('reservation_expires_at', models.DateTimeField()),
                ('session_created_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_checkout_attempts', to=settings.AUTH_USER_MODEL)),
                ('founder_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_attempts', to='SalesLogApp.foundergrant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductory_benefit_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('introductory_benefit_kind', models.CharField(blank=True, choices=[('', 'None'), ('standard', 'Standard'), ('founder', 'Founder')], default='', max_length=12)),
                ('founder_entitlement_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=64)),
                ('last_event_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_synchronized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authoritative_subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleslog_billing_access', to='djstripe.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_access', to=settings.AUTH_USER_MODEL)),
                ('founder_grant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_access', to='SalesLogApp.foundergrant')),
            ],
            options={
                'verbose_name_plural': 'billing access records',
            },
        ),
        migrations.AddConstraint(
            model_name='foundergrant',
            constraint=models.CheckConstraint(condition=models.Q(('max_redemptions__gte', 1)), name='founder_grant_max_redemptions_positive'),
        ),
        migrations.AddConstraint(
            model_name='foundergrant',
            constraint=models.CheckConstraint(condition=models.Q(('redemption_count__lte', models.F('max_redemptions'))), name='founder_grant_redemptions_within_max'),
        ),
        migrations.AddIndex(
            model_name='billingcheckoutattempt',
            index=models.Index(fields=['user', 'status', 'reservation_expires_at'], name='billing_attempt_user_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcheckoutattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'session_created', 'checkout_completed'])), fields=('user',), name='one_active_billing_checkout_per_user'),
        ),
        migrations.AddConstraint(
            model_name='billingcheckoutattempt',
            constraint=models.CheckConstraint(condition=models.Q(('trial_days__lte', 365)), name='billing_checkout_trial_days_bounded'),
        ),
    ]
