# Generated by Django 5.2.15 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0055_team_email_invitations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationDispatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('recipient_digest', models.CharField(max_length=64, unique=True)),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('backfill', 'Existing-user verification backfill'),
                            ('team_join', 'Team invitation verification'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('sent', 'Sent'),
                            ('skipped', 'Skipped'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=12,
                    ),
                ),
                ('attempted_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='email_verification_dispatches',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='emailverificationdispatch',
            index=models.Index(
                fields=['user', 'status', 'attempted_at'],
                name='sl_ev_user_status_attempt',
            ),
        ),
    ]
