# Generated by Django 5.2.15 on 2026-08-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0057_monthlygoal_target_total_gross'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingDayClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_day_closures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['user', 'date'], name='closure_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_selling_day_closure_user_date'), models.CheckConstraint(condition=models.Q(('date__week_day', 1), _negated=True), name='selling_day_closure_not_sunday')],
            },
        ),
    ]
