# Generated by Django 5.2.15 on 2026-08-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0058_selling_day_closure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StewCoachNudgeDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_key', models.CharField(choices=[('set_goals', 'Set monthly goals'), ('log_activity', 'Log daily activity'), ('behind_pace', 'Behind pace'), ('month_end_push', 'Month-end push')], max_length=32)),
                ('month_start', models.DateField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stew_coach_nudge_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_start', 'nudge_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'nudge_key', 'month_start'), name='unique_stew_nudge_dismissal_user_key_month')],
            },
        ),
    ]
