# Generated by Django 5.2.15 on 2026-08-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0059_stewcoachnudgedismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccess',
            name='onboarding_required_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
