# Generated by Django 5.2.15 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0060_billingaccess_onboarding_required_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcheckoutattempt',
            name='selected_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billingcheckoutattempt',
            name='selected_tier',
            field=models.CharField(
                choices=[('basic', 'Basic'), ('pro', 'Pro')],
                default='pro',
                max_length=12,
            ),
        ),
    ]
