# Generated by Django 5.2.15 on 2026-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0061_billingcheckoutattempt_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcheckoutattempt',
            name='selected_billing_interval',
            field=models.CharField(
                choices=[('month', 'Monthly'), ('year', 'Yearly')],
                default='month',
                max_length=5,
            ),
        ),
    ]
