# Generated by Django 5.2.15 on 2026-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0062_billingcheckoutattempt_selected_billing_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccess',
            name='enforcement_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaccess',
            name='enforcement_grace_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaccess',
            name='enforcement_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
