# Generated by Django 5.2.15 on 2026-08-24 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesLogApp', '0063_bill4_staged_billing_enforcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskStewConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='open', max_length=16)),
                ('last_intent', models.CharField(blank=True, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_stew_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AskStewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
                ('submission_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('intent', models.CharField(blank=True, max_length=48)),
                ('route_source', models.CharField(blank=True, choices=[('deterministic', 'Deterministic'), ('provider_router', 'Provider router'), ('declined', 'Declined'), ('safe_fallback', 'Safe fallback')], max_length=24)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('provider_used', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('source_label', models.CharField(blank=True, max_length=160)),
                ('notice', models.CharField(blank=True, max_length=500)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='SalesLogApp.askstewconversation')),
                ('reply_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='SalesLogApp.askstewturn')),
            ],
            options={
                'ordering': ['conversation', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='AskStewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_stew_feedback', to=settings.AUTH_USER_MODEL)),
                ('assistant_turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='SalesLogApp.askstewturn')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='askstewconversation',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='ask_stew_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='askstewturn',
            index=models.Index(fields=['conversation', 'created_at'], name='ask_stew_conv_time_idx'),
        ),
        migrations.AddIndex(
            model_name='askstewturn',
            index=models.Index(fields=['intent', 'route_source', 'created_at'], name='ask_stew_route_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='askstewturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='unique_ask_stew_turn_sequence'),
        ),
        migrations.AddConstraint(
            model_name='askstewturn',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_ref', ''), _negated=True), fields=('conversation', 'submission_ref'), name='unique_ask_stew_submission_ref'),
        ),
        migrations.AddIndex(
            model_name='askstewfeedback',
            index=models.Index(fields=['helpful', 'updated_at'], name='ask_stew_helpful_time_idx'),
        ),
    ]
