"""
Django settings for SalesLog project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import ipaddress
import secrets
import socket
from urllib.parse import urlsplit

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_strict_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {'1', 'true'}:
        return True
    if normalized in {'0', 'false'}:
        return False
    raise ImproperlyConfigured(
        f'{name} must be one of: true, false, 1, or 0.'
    )


def env_int(name, default, *, minimum=1):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return default
    return parsed if parsed >= minimum else default


def env_bounded_int(name, default, *, minimum, maximum):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc
    if not minimum <= parsed <= maximum:
        raise ImproperlyConfigured(
            f'{name} must be between {minimum} and {maximum}.'
        )
    return parsed


def env_list(name):
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]


DEBUG = env_bool('DEBUG', True)

# Optional Pay Plan Assistant provider. External calls are opt-in and the API
# key is read only inside the provider adapter for readiness and request use.
PAY_PLAN_ASSISTANT_PROVIDER_ENABLED = env_bool(
    'PAY_PLAN_ASSISTANT_PROVIDER_ENABLED', False,
)
PAY_PLAN_ASSISTANT_PROVIDER = os.getenv(
    'PAY_PLAN_ASSISTANT_PROVIDER', 'openai',
).strip().lower()
PAY_PLAN_ASSISTANT_MODEL = os.getenv(
    'PAY_PLAN_ASSISTANT_MODEL', 'gpt-5.6-sol',
).strip() or 'gpt-5.6-sol'
# Provider-facing values remain raw so the readiness diagnostic can distinguish
# invalid deployment configuration from a valid default.
PAY_PLAN_ASSISTANT_TIMEOUT_SECONDS = os.getenv(
    'PAY_PLAN_ASSISTANT_TIMEOUT_SECONDS', '10',
).strip()
PAY_PLAN_ASSISTANT_ROLLOUT_PERCENT = os.getenv(
    'PAY_PLAN_ASSISTANT_ROLLOUT_PERCENT', '0',
).strip()
PAY_PLAN_ASSISTANT_ALLOWED_USER_IDS = env_list(
    'PAY_PLAN_ASSISTANT_ALLOWED_USER_IDS',
)
PAY_PLAN_ASSISTANT_DAILY_REQUEST_LIMIT = os.getenv(
    'PAY_PLAN_ASSISTANT_DAILY_REQUEST_LIMIT', '20',
).strip()
PAY_PLAN_ASSISTANT_MAX_PROVIDER_INPUT_CHARS = os.getenv(
    'PAY_PLAN_ASSISTANT_MAX_PROVIDER_INPUT_CHARS', '8000',
).strip()
PAY_PLAN_ASSISTANT_MAX_PROVIDER_RESPONSE_BYTES = os.getenv(
    'PAY_PLAN_ASSISTANT_MAX_PROVIDER_RESPONSE_BYTES', '65536',
).strip()
PAY_PLAN_ASSISTANT_MAX_OUTPUT_TOKENS = os.getenv(
    'PAY_PLAN_ASSISTANT_MAX_OUTPUT_TOKENS', '600',
).strip()
PAY_PLAN_ASSISTANT_MAX_TURNS = env_int('PAY_PLAN_ASSISTANT_MAX_TURNS', 12)
PAY_PLAN_ASSISTANT_CONVERSATION_TTL_HOURS = env_int(
    'PAY_PLAN_ASSISTANT_CONVERSATION_TTL_HOURS', 24,
)
PAY_PLAN_ASSISTANT_EVENT_RETENTION_DAYS = env_int(
    'PAY_PLAN_ASSISTANT_EVENT_RETENTION_DAYS', 30,
)

# CX-3 Ask Stew AI pilot access is deliberately independent from Stripe and
# the legacy pay-plan-change assistant rollout. Only immutable user IDs listed
# here receive customer access; an empty list denies every non-staff user.
ASK_STEW_AI_PILOT_USER_IDS = env_list('ASK_STEW_AI_PILOT_USER_IDS')
# AI-1A starts as an in-house lab. While this is true, customer allowlist IDs
# cannot grant access; authenticated staff and superusers remain authorized.
ASK_STEW_AI_LAB_ONLY = env_strict_bool('ASK_STEW_AI_LAB_ONLY', True)
ASK_STEW_AI_MAX_TURNS = env_bounded_int(
    'ASK_STEW_AI_MAX_TURNS', 12, minimum=2, maximum=40,
)
ASK_STEW_AI_CONVERSATION_TTL_HOURS = env_bounded_int(
    'ASK_STEW_AI_CONVERSATION_TTL_HOURS', 24, minimum=1, maximum=168,
)
ASK_STEW_AI_SHORT_WINDOW_SECONDS = env_bounded_int(
    'ASK_STEW_AI_SHORT_WINDOW_SECONDS', 60, minimum=10, maximum=3600,
)
ASK_STEW_AI_SHORT_WINDOW_LIMIT = env_bounded_int(
    'ASK_STEW_AI_SHORT_WINDOW_LIMIT', 6, minimum=1, maximum=100,
)
ASK_STEW_AI_CONVERSATION_RETENTION_DAYS = env_bounded_int(
    'ASK_STEW_AI_CONVERSATION_RETENTION_DAYS', 30, minimum=1, maximum=365,
)

# Phase 2A Teams is dark-launched. This flag is deliberately strict so a
# misspelled production value cannot accidentally enable a social surface.
TEAMS_FEATURE_ENABLED = env_strict_bool('TEAMS_FEATURE_ENABLED', False)
TEAMS_ENTITLEMENT_BACKEND = os.getenv(
    'TEAMS_ENTITLEMENT_BACKEND',
    'SalesLogApp.team_entitlements.billing_owned_entitlement',
).strip()
TEAMS_FOUNDER_USER_IDS = env_list('TEAMS_FOUNDER_USER_IDS')
TEAMS_INVITATION_TTL_HOURS = env_int('TEAMS_INVITATION_TTL_HOURS', 168)
_team_invitation_ttl_seconds = TEAMS_INVITATION_TTL_HOURS * 60 * 60
TEAM_INVITATION_VERIFICATION_RESUME_MAX_AGE = env_bounded_int(
    'TEAM_INVITATION_VERIFICATION_RESUME_MAX_AGE',
    min(_team_invitation_ttl_seconds, 7 * 24 * 60 * 60),
    minimum=1,
    maximum=7 * 24 * 60 * 60,
)
if TEAM_INVITATION_VERIFICATION_RESUME_MAX_AGE > _team_invitation_ttl_seconds:
    raise ImproperlyConfigured(
        'TEAM_INVITATION_VERIFICATION_RESUME_MAX_AGE cannot exceed the '
        'configured team invitation lifetime.'
    )
EMAIL_VERIFICATION_RESEND_COOLDOWN_MINUTES = env_bounded_int(
    'EMAIL_VERIFICATION_RESEND_COOLDOWN_MINUTES',
    60,
    minimum=3,
    maximum=1440,
)
EMAIL_VERIFICATION_PENDING_STALE_MINUTES = env_bounded_int(
    'EMAIL_VERIFICATION_PENDING_STALE_MINUTES',
    15,
    minimum=1,
    maximum=1440,
)

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is false.')
    # Keep local startup convenient without committing a reusable signing key.
    # Set SECRET_KEY locally when stable development sessions are desired.
    SECRET_KEY = secrets.token_urlsafe(50)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_hostname:
    if render_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_hostname)
    render_origin = f'https://{render_hostname}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)


def _local_private_ipv4_addresses():
    addresses = set()
    try:
        hostname = socket.gethostname()
        for family, _, _, _, sockaddr in socket.getaddrinfo(hostname, None):
            if family != socket.AF_INET:
                continue
            host = sockaddr[0]
            ip = ipaddress.ip_address(host)
            if ip.is_private:
                addresses.add(host)
    except OSError:
        pass

    try:
        # Detect the currently active interface address without sending traffic.
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
            probe.connect(('8.8.8.8', 80))
            host = probe.getsockname()[0]
            ip = ipaddress.ip_address(host)
            if ip.is_private:
                addresses.add(host)
    except OSError:
        pass

    return sorted(addresses)


if DEBUG:
    debug_hosts = {'localhost', '127.0.0.1', '[::1]'}
    debug_hosts.update(_local_private_ipv4_addresses())
    for host in sorted(debug_hosts):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

    # Development-only origins for local-network phone testing.
    for host in sorted(debug_hosts):
        if host == '[::1]':
            continue
        origin = f'http://{host}:8000'
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'SalesLogApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djstripe',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Social providers (e.g., Google, Apple)
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'SalesLogApp.billing_middleware.BillingEnforcementMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'SalesLog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'login'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SalesLogApp.profile_context.appearance',
                'SalesLogApp.billing_enforcement_context.enforcement_notice',
            ],
        },
    },
]

WSGI_APPLICATION = 'SalesLog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = os.getenv('MEDIA_URL', '/media/').strip() or '/media/'
if not MEDIA_URL.startswith('/'):
    MEDIA_URL = f'/{MEDIA_URL}'
if not MEDIA_URL.endswith('/'):
    MEDIA_URL = f'{MEDIA_URL}/'
_configured_media_root = os.getenv('MEDIA_ROOT', '').strip()
MEDIA_ROOT = (
    Path(_configured_media_root).expanduser()
    if _configured_media_root
    else BASE_DIR / 'media'
)
if not MEDIA_ROOT.is_absolute():
    MEDIA_ROOT = BASE_DIR / MEDIA_ROOT

# Upload size limits (default 20 MB)
MAX_UPLOAD_SIZE_MB = int(os.getenv('MAX_UPLOAD_SIZE_MB', '20'))
_max_upload_bytes = MAX_UPLOAD_SIZE_MB * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = _max_upload_bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = _max_upload_bytes

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = 0 if DEBUG else 31536000

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'


)

STRIPE_LIVE_MODE = env_strict_bool('STRIPE_LIVE_MODE', False)
STRIPE_TEST_PUBLIC_KEY = os.getenv('STRIPE_TEST_PUBLIC_KEY', '').strip()
STRIPE_TEST_SECRET_KEY = os.getenv('STRIPE_TEST_SECRET_KEY', '').strip()
STRIPE_LIVE_PUBLIC_KEY = os.getenv('STRIPE_LIVE_PUBLIC_KEY', '').strip()
STRIPE_LIVE_SECRET_KEY = os.getenv('STRIPE_LIVE_SECRET_KEY', '').strip()
STRIPE_BASIC_MONTHLY_PRICE_ID = os.getenv(
    'STRIPE_BASIC_MONTHLY_PRICE_ID', ''
).strip()
STRIPE_BASIC_YEARLY_PRICE_ID = os.getenv(
    'STRIPE_BASIC_YEARLY_PRICE_ID', ''
).strip()
STRIPE_PRO_MONTHLY_PRICE_ID = os.getenv(
    'STRIPE_PRO_MONTHLY_PRICE_ID', ''
).strip()
STRIPE_PRO_YEARLY_PRICE_ID = os.getenv(
    'STRIPE_PRO_YEARLY_PRICE_ID', ''
).strip()
STRIPE_LEGACY_PRO_PRICE_IDS = env_list('STRIPE_LEGACY_PRO_PRICE_IDS')

BILLING_FEATURE_ENABLED = env_strict_bool('BILLING_FEATURE_ENABLED', False)
BILLING_ENFORCEMENT_ENABLED = env_strict_bool(
    'BILLING_ENFORCEMENT_ENABLED', False
)
BILLING_ENFORCEMENT_EMERGENCY_BYPASS = env_strict_bool(
    'BILLING_ENFORCEMENT_EMERGENCY_BYPASS', False
)
BILLING_ONBOARDING_ENABLED = env_strict_bool(
    'BILLING_ONBOARDING_ENABLED', False
)
BILLING_TIERED_PRICING_ENABLED = env_strict_bool(
    'BILLING_TIERED_PRICING_ENABLED', False
)
BILLING_STANDARD_TRIAL_DAYS = env_bounded_int(
    'BILLING_STANDARD_TRIAL_DAYS', 30, minimum=1, maximum=365
)
BILLING_FOUNDER_TRIAL_DAYS = env_bounded_int(
    'BILLING_FOUNDER_TRIAL_DAYS', 90, minimum=1, maximum=365
)
BILLING_CHECKOUT_RESERVATION_MINUTES = 60
BILLING_PAST_DUE_GRACE_DAYS = 7

DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"
DJSTRIPE_WEBHOOK_VALIDATION = "verify_signature"
DJSTRIPE_SUBSCRIBER_CUSTOMER_KEY = "djstripe_subscriber"

LOGIN_REDIRECT_URL = '/SalesLogApp/pay-plan/setup/'

# settings.py
ACCOUNT_LOGIN_REDIRECT_URL = '/SalesLogApp/pay-plan/setup/'
# Email is the stable identity boundary for account recovery and Teams
# invitations. Verification remains optional for general beta access, but a
# verified address is required before an emailed Team invitation can be used.
ACCOUNT_SIGNUP_FIELDS = [
    'username*',
    'email*',
    'password1*',
    'password2*',
]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_ADAPTER = 'SalesLogApp.account_adapter.StewLogAccountAdapter'
EMAIL_VERIFICATION_PUBLIC_BASE_URL = os.getenv(
    'EMAIL_VERIFICATION_PUBLIC_BASE_URL',
    'http://localhost:8000' if DEBUG else '',
).strip().rstrip('/')

if not DEBUG:
    verification_base = urlsplit(EMAIL_VERIFICATION_PUBLIC_BASE_URL)
    if (
        EMAIL_VERIFICATION_PUBLIC_BASE_URL != 'https://stewlog.com'
        or verification_base.scheme != 'https'
        or not verification_base.hostname
        or verification_base.hostname not in ALLOWED_HOSTS
        or verification_base.path not in {'', '/'}
        or verification_base.query
        or verification_base.fragment
    ):
        raise ImproperlyConfigured(
            'EMAIL_VERIFICATION_PUBLIC_BASE_URL must be the canonical StewLog '
            'HTTPS origin in production.'
        )

# Email
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    (
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = env_bounded_int('EMAIL_PORT', 587, minimum=1, maximum=65535)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = env_bounded_int('EMAIL_TIMEOUT', 10, minimum=1, maximum=300)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

if (
    not DEBUG
    and EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend'
    and not EMAIL_HOST
):
    raise ImproperlyConfigured(
        'EMAIL_HOST must be set when using the SMTP email backend in production.'
    )

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
