from .evaluators import (
    BackGrossPercentageEvaluator,
    DeductionEvaluator,
    FlatBackendCommissionEvaluator,
    FlatPerDealEvaluator,
    FrontGrossPercentageEvaluator,
    ProgressiveUnitPositionPercentageEvaluator,
    TieredMinimumCommissionEvaluator,
    ManualAdjustmentEvaluator,
    MaximumCommissionEvaluator,
    MinimumCommissionEvaluator,
    PeriodQualificationBonusEvaluator,
    PerUnitBonusEvaluator,
    VehicleSpiffEvaluator,
    VolumeBonusEvaluator,
    SurveyCountBonusEvaluator,
    AcquisitionBonusEvaluator,
)

RULE_TYPE_REGISTRY = {
    'front_gross_percentage': FrontGrossPercentageEvaluator,
    'progressive_unit_position_percentage': ProgressiveUnitPositionPercentageEvaluator,
    'tiered_minimum_commission': TieredMinimumCommissionEvaluator,
    'back_gross_percentage': BackGrossPercentageEvaluator,
    'flat_per_deal': FlatPerDealEvaluator,
    'flat_backend_commission': FlatBackendCommissionEvaluator,
    'minimum_commission': MinimumCommissionEvaluator,
    'maximum_commission': MaximumCommissionEvaluator,
    'volume_bonus': VolumeBonusEvaluator,
    'per_unit_bonus': PerUnitBonusEvaluator,
    'vehicle_spiff': VehicleSpiffEvaluator,
    'manual_adjustment': ManualAdjustmentEvaluator,
    'deduction': DeductionEvaluator,
    'period_qualification_bonus': PeriodQualificationBonusEvaluator,
    'survey_count_bonus': SurveyCountBonusEvaluator,
    'acquisition_bonus': AcquisitionBonusEvaluator,
}
